name: OS Update

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

concurrency:
  group: os-update
  cancel-in-progress: true

jobs:
  update-os:
    runs-on: ubuntu-latest
    env:
      RUN_OS_UPDATE: "false"
      REBOOT_IF_NEEDED: "false"
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && env.RUN_OS_UPDATE == 'true') }}
    timeout-minutes: 60
    
    outputs:
      upgrade_list: ${{ steps.parse_outputs.outputs.upgrade_list }}
      disk_space_before: ${{ steps.parse_outputs.outputs.disk_space_before }}
      disk_space_after: ${{ steps.parse_outputs.outputs.disk_space_after }}
      update_count: ${{ steps.parse_outputs.outputs.update_count }}
    
    steps:
      - id: update_os_step
        name: Update OS via SSH and Generate Summary
        uses: appleboy/ssh-action@master
        env: 
          REBOOT_FLAG: ${{ env.REBOOT_IF_NEEDED }}
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            set -eo pipefail
            export NEEDRESTART_MODE=a
            export DEBIAN_FRONTEND=noninteractive
            
            # Generate unique output file ON REMOTE SERVER
            OUTPUT_FILE="/tmp/update_os_$(date +%s).txt"
            SUMMARY_FILE="/tmp/os_update_summary.txt"
            
            # Store the path for retrieval
            echo "OUTPUT_FILE_PATH=$OUTPUT_FILE" > /tmp/output_marker.txt
            
            # Disk check
            DISK_SPACE_BEFORE=$(df -h / | awk 'NR==2 {print $4}')
            AVAIL_SPACE_KB=$(df / | awk 'NR==2 {print $4}')
            (( $AVAIL_SPACE_KB < 1048576 )) && { echo "Insufficient disk space"; exit 1; }

            # Package operations
            sudo apt-get -qy clean
            sudo apt-get -qy update
            
            # Capture and redirect to file
            echo "upgrade_list=" >> "$OUTPUT_FILE"
            {
              sudo apt list --upgradable 2>/dev/null | grep -v "Listing..."
            } >> "$OUTPUT_FILE"
            
            UPDATE_COUNT=$(sudo apt list --upgradable 2>/dev/null | grep -v "Listing..." | wc -l)

            # Perform upgrade
            sudo apt-get -qy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
            sudo apt-get -qy autoremove

            # Post-update
            DISK_SPACE_AFTER=$(df -h / | awk 'NR==2 {print $4}')

            # Write outputs
            {
              echo "disk_space_before=$DISK_SPACE_BEFORE"
              echo "disk_space_after=$DISK_SPACE_AFTER"
              echo "update_count=$UPDATE_COUNT"
            } >> "$OUTPUT_FILE"
            chmod 600 "$OUTPUT_FILE"

            # Reboot handling
            if [[ "$REBOOT_FLAG" = "true" && -f /var/run/reboot-required ]]; then
              sudo nohup reboot </dev/null &>/dev/null &
              exit 0
            fi
            
            # Debugging and Summary Generation
            echo "## OS Update Summary" > "$SUMMARY_FILE"
            echo "**Status:** success" >> "$SUMMARY_FILE"
            echo "✅ Updated $UPDATE_COUNT packages" >> "$SUMMARY_FILE"
            echo "💽 Disk space before: $DISK_SPACE_BEFORE" >> "$SUMMARY_FILE"
            echo "💽 Disk space after: $DISK_SPACE_AFTER" >> "$SUMMARY_FILE"
            
            if [[ -f "$OUTPUT_FILE" ]]; then
              echo "Output file exists: $OUTPUT_FILE"
              ls -lah "$OUTPUT_FILE"
              cat "$OUTPUT_FILE"
              
              UPGRADE_LIST=$(awk '/upgrade_list=/{flag=1; next} /EOF/{flag=0} flag' "$OUTPUT_FILE")

              if [[ -n "$UPGRADE_LIST" ]]; then
                echo "### 📦 Upgraded Packages" >> "$SUMMARY_FILE"
                echo '```' >> "$SUMMARY_FILE"
                echo "$UPGRADE_LIST" >> "$SUMMARY_FILE"
                echo '```' >> "$SUMMARY_FILE"
              else
                echo "No packages upgraded" >> "$SUMMARY_FILE"
              fi
            else
              echo "Output file does NOT exist!"
              echo "No updates were performed." >> "$SUMMARY_FILE"
            fi
            
            echo "SUMMARY_FILE_PATH=$SUMMARY_FILE" > /tmp/summary_marker.txt

      - name: Extract Output File Path
        id: extract_path
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cat /tmp/output_marker.txt 2>/dev/null || echo "No output file found"

      - name: Parse Output File Path
        id: parse_output_path
        run: |
          FILE_PATH=$(echo "${{ steps.extract_path.outputs.stdout }}" | grep "OUTPUT_FILE_PATH" | cut -d= -f2)
          echo "output_file=$FILE_PATH" >> $GITHUB_OUTPUT

      - name: Extract Summary File Path
        id: extract_summary
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cat /tmp/summary_marker.txt 2>/dev/null || echo "No summary file found"

      - name: Parse Summary File Path
        id: parse_summary_path
        run: |
          SUMMARY_FILE=$(echo "${{ steps.extract_summary.outputs.stdout }}" | grep "SUMMARY_FILE_PATH" | cut -d= -f2)
          echo "summary_file=$SUMMARY_FILE" >> $GITHUB_OUTPUT

      - name: Retrieve and Append Job Summary
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cat "${{ steps.parse_summary_path.outputs.summary_file }}" 2>/dev/null || echo "No summary file found"
      - name: Append to GitHub Summary
        run: |
          echo "${{ steps.retrieve_summary.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
